project_id = "mrwbbwdvtndgaewwwdko"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.ai-assistant-chat]
verify_jwt = false

[functions.bible-verse-ai-search]
verify_jwt = false

[functions.chatgpt-action]
verify_jwt = false

[functions.check-achievements]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.daily-devotional-reminder]
verify_jwt = false

[functions.generate-achievement-badge]
verify_jwt = false

[functions.generate-devotionals]
verify_jwt = false

[functions.generate-prayer]
verify_jwt = false

[functions.journey-reminder]
verify_jwt = false

[functions.prayer-journal-reminder]
verify_jwt = false

[functions.rate-limit]
verify_jwt = false

[functions.recommend-resources]
verify_jwt = false

[functions.response-coach]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-results-email]
verify_jwt = false

[functions.study-recommendations]
verify_jwt = false

[functions.study-reminder]
verify_jwt = false

[functions.subscribe-push]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.send-qa-answer-notification]
verify_jwt = false

[functions.notify-video-suggestion]
verify_jwt = false

[functions.notify-healing-story]
verify_jwt = false

[functions.notify-story-approved]
verify_jwt = false

[functions.recommend-video]
verify_jwt = false

[functions.send-targeted-notification]
verify_jwt = false

[functions.text-to-speech-article]
verify_jwt = false

[functions.notify-coaching-waitlist]
verify_jwt = false
